import { describe, expect, it } from "vitest";
import { checkInReport, detectDistress, distressLevel, isMachineGreeting, type CheckInTopic } from "./index.js";

// The 480 inputs of an independent blind probe (written before reading any source, 2026-10-02): 200 check-in
// exchanges, 200 distress lines, 80 lines heard from the other end, with that probe's expectations.
// Do not delete or loosen a row to make a change pass.

const QUESTIONS: Record<CheckInTopic, string> = {"condition": "今日の体調はいかがですか。お元気ですか。", "meal": "今日はお食事は召し上がりましたか。", "medication": "お薬は飲まれましたか。", "sleep": "昨夜はよく眠れましたか。", "help": "何か困っていることはありますか。"};
// [topic, expectation, turns]. "@Q" is the standard question; "c:" the agent, "e:" the person.
// "yes" / "no": a plain answer, recorded exactly. "!yes": must not be yes. "!no" (help): must not be "nothing to raise".
const EXCHANGES: [CheckInTopic, "yes" | "no" | "!yes" | "!no", ...string[]][] = [
  ["condition", "!yes", "@Q", "e:あんまりよくないねえ。"],
  ["condition", "!yes", "@Q", "e:腰が痛くてね。"],
  ["condition", "!yes", "@Q", "e:元気じゃないよ。"],
  ["condition", "!yes", "@Q", "e:元気だったらいいんだけどねえ。"],
  ["condition", "!yes", "@Q", "e:昨日までは元気だったんだけど、今朝から熱があって。"],
  ["condition", "!yes", "@Q", "e:大丈夫じゃない。"],
  ["condition", "!yes", "@Q", "e:元気、と言いたいところだけど、めまいがするんよ。"],
  ["condition", "!yes", "@Q", "e:はい？なんて？"],
  ["condition", "!yes", "@Q", "e:元気です。…いや、本当は朝からずっと頭が痛いの。"],
  ["condition", "!yes", "@Q", "e:しんどいわ。あかんわ今日は。"],
  ["condition", "!yes", "@Q", "e:なんだがこわくてなぁ、起ぎらんねぇのよ。"],
  ["condition", "!yes", "@Q", "e:きつかとよ。体のだるうして。"],
  ["condition", "!yes", "@Q", "e:えらいんよ。たいぎいわ。"],
  ["condition", "!yes", "@Q", "e:えらいでかんわ。"],
  ["condition", "!yes", "@Q", "e:あんまりよくないですねひざがいたくて"],
  ["condition", "!yes", "@Q", "e:娘は元気ですよ。"],
  ["condition", "!yes", "@Q", "e:元気かって？さあ、どうだろうね。"],
  ["condition", "!yes", "@Q", "e:よくはないね。"],
  ["condition", "!yes", "@Q", "e:変わりないけど、相変わらず悪いよ。"],
  ["condition", "!yes", "@Q", "e:はい。…はい、なんでしたっけ。"],
  ["condition", "!yes", "@Q", "e:風邪ひいたみたいで咳が出る。"],
  ["condition", "!yes", "@Q", "e:元気なわけないでしょう、この年で。"],
  ["condition", "!yes", "@Q", "e:悪くはないけど、良くもない。"],
  ["condition", "!yes", "@Q", "e:元気ですよ。", "c:それはよかったです。", "e:でもね、ゆうべ転んで足が腫れてるの。"],
  ["meal", "!yes", "@Q", "e:まだ食べてない。"],
  ["meal", "!yes", "@Q", "e:食欲がなくてね、食べられないの。"],
  ["meal", "!yes", "@Q", "e:食べたかどうか、覚えてないねえ。"],
  ["meal", "!yes", "@Q", "e:ほとんど食べてない。"],
  ["meal", "!yes", "@Q", "e:食べようと思ったけど、作るのが面倒で。"],
  ["meal", "!yes", "@Q", "e:これから食べるところ。"],
  ["meal", "!yes", "@Q", "e:食べたくない。"],
  ["meal", "!yes", "@Q", "e:はい、食べ…てないわ、今日は。"],
  ["meal", "!yes", "@Q", "e:昨日は食べたよ。"],
  ["meal", "!yes", "@Q", "e:食べられんのよ、喉を通らん。"],
  ["meal", "!yes", "@Q", "e:食べてへん。"],
  ["meal", "!yes", "@Q", "e:まだ食べてへんねん。"],
  ["meal", "!yes", "@Q", "e:まだ食ってねぇのよ。"],
  ["meal", "!yes", "@Q", "e:食べとらんよ。"],
  ["meal", "!yes", "@Q", "e:食べとらんのんよ。"],
  ["meal", "!yes", "@Q", "e:食べとらんがね。"],
  ["meal", "!yes", "@Q", "e:たべてませんしょくよくがなくて"],
  ["meal", "!yes", "@Q", "e:猫にはやったけどね。"],
  ["meal", "!yes", "@Q", "e:食べたかねえ…どうだったかねえ。"],
  ["meal", "!yes", "@Q", "e:ヘルパーさんが来てから食べる。"],
  ["meal", "!yes", "@Q", "e:食べる気がしない。"],
  ["meal", "!yes", "@Q", "e:何も口にしてない。"],
  ["meal", "!yes", "@Q", "e:食べたらすぐ吐いてしまうから、食べてないの。"],
  ["meal", "!yes", "@Q", "e:食べました。", "c:何を召し上がりましたか。", "e:…あれ、食べたのは昨日だったかな。今日はまだだわ。"],
  ["medication", "!yes", "@Q", "e:飲み忘れた。"],
  ["medication", "!yes", "@Q", "e:まだ飲んでない。"],
  ["medication", "!yes", "@Q", "e:飲んだかどうかわからない。"],
  ["medication", "!yes", "@Q", "e:薬が切れてしまって、ないの。"],
  ["medication", "!yes", "@Q", "e:飲みたくない。あれ飲むと気持ち悪くなる。"],
  ["medication", "!yes", "@Q", "e:朝のは飲んだけど、昼のは忘れた。"],
  ["medication", "!yes", "@Q", "e:飲んだと思うけど…自信ない。"],
  ["medication", "!yes", "@Q", "e:あとで飲みます。"],
  ["medication", "!yes", "@Q", "e:薬？どこに置いたかわからんのよ。"],
  ["medication", "!yes", "@Q", "e:飲んでへん。忘れてたわ。"],
  ["medication", "!yes", "@Q", "e:飲んでねぇ。"],
  ["medication", "!yes", "@Q", "e:飲んどらん。"],
  ["medication", "!yes", "@Q", "e:飲んどらんよ。"],
  ["medication", "!yes", "@Q", "e:まだ飲んどらんわ。"],
  ["medication", "!yes", "@Q", "e:のみわすれましたすいません"],
  ["medication", "!yes", "@Q", "e:飲みました…あ、違う、それは昨日だ。今日はまだ。"],
  ["medication", "!yes", "@Q", "e:先生がもう飲まなくていいって。"],
  ["medication", "!yes", "@Q", "e:やめたの、もう。"],
  ["medication", "!yes", "@Q", "e:飲めって言われてるけどねえ。"],
  ["medication", "!yes", "@Q", "e:夫は飲みましたよ。"],
  ["medication", "!yes", "@Q", "e:これから。"],
  ["medication", "!yes", "@Q", "e:はい？薬？なんの薬？"],
  ["medication", "!yes", "@Q", "e:飲んだような、飲まないような。"],
  ["medication", "!yes", "@Q", "e:ご飯のあとに飲むから、まだ。"],
  ["sleep", "!yes", "@Q", "e:全然眠れなかった。"],
  ["sleep", "!yes", "@Q", "e:何度も目が覚めてね。"],
  ["sleep", "!yes", "@Q", "e:眠れたらいいんだけど。"],
  ["sleep", "!yes", "@Q", "e:2時間くらいしか寝てない。"],
  ["sleep", "!yes", "@Q", "e:夜中にトイレに5回も起きて。"],
  ["sleep", "!yes", "@Q", "e:寝つけなくて、朝方ようやく。"],
  ["sleep", "!yes", "@Q", "e:眠れん。"],
  ["sleep", "!yes", "@Q", "e:寝られへんかった。"],
  ["sleep", "!yes", "@Q", "e:寝らんねがった。"],
  ["sleep", "!yes", "@Q", "e:眠れんやった。"],
  ["sleep", "!yes", "@Q", "e:寝れんかったんよ。"],
  ["sleep", "!yes", "@Q", "e:寝れんかったがね。"],
  ["sleep", "!yes", "@Q", "e:あんまりねむれませんでした"],
  ["sleep", "!yes", "@Q", "e:よく眠れたとは言えないね。"],
  ["sleep", "!yes", "@Q", "e:眠れたかって？眠れるわけないよ、足が痛くて。"],
  ["sleep", "!yes", "@Q", "e:昼間は寝てるんだけど、夜はだめ。"],
  ["sleep", "!yes", "@Q", "e:はい、眠れ…なかったね、ゆうべは。"],
  ["sleep", "!yes", "@Q", "e:どうだったかな、覚えてない。"],
  ["sleep", "!yes", "@Q", "e:眠剤を飲んでもだめだった。"],
  ["sleep", "!yes", "@Q", "e:一睡もしてない。"],
  ["sleep", "!yes", "@Q", "e:隣の犬がうるさくて。"],
  ["sleep", "!yes", "@Q", "e:眠れました。", "c:それはよかったです。", "e:でも怖い夢を見て夜中に起きてからは、朝まで起きてた。"],
  ["sleep", "!yes", "@Q", "e:うとうとしただけ。"],
  ["sleep", "!yes", "@Q", "e:さあ。"],
  ["help", "!no", "@Q", "e:電球が切れて、替えられないの。"],
  ["help", "!no", "@Q", "e:特にないけど、お風呂の給湯器が壊れてて。"],
  ["help", "!no", "@Q", "e:ないと言えばないけど、買い物に行けなくて困ってる。"],
  ["help", "!no", "@Q", "e:困ってることだらけよ。"],
  ["help", "!no", "@Q", "e:ないことはない。"],
  ["help", "!no", "@Q", "e:お金がなくてね。"],
  ["help", "!no", "@Q", "e:足が悪くて病院に行けない。"],
  ["help", "!no", "@Q", "e:別に…まあ、さみしいくらいかな。"],
  ["help", "!no", "@Q", "e:困ってるねん、エアコンがつかへん。"],
  ["help", "!no", "@Q", "e:灯油運べねくて困ってんだ。"],
  ["help", "!no", "@Q", "e:困っとうとよ、テレビの映らんで。"],
  ["help", "!no", "@Q", "e:困っとるんよ、鍵をなくしてしもうて。"],
  ["help", "!no", "@Q", "e:困っとるがね、水が出んでよ。"],
  ["help", "!no", "@Q", "e:といれのみずがながれなくてこまってます"],
  ["help", "!no", "@Q", "e:大丈夫じゃないのよ、それが。"],
  ["help", "!no", "@Q", "e:ありません。…あ、そうだ、ひとつあった。薬がもうすぐなくなる。"],
  ["help", "!no", "@Q", "e:何もない、わけじゃないんだけど。"],
  ["help", "!no", "@Q", "e:言ってもしょうがないけどね。"],
  ["help", "!no", "@Q", "e:あるよ。"],
  ["help", "!no", "@Q", "e:はい。"],
  ["help", "!no", "@Q", "e:耳が遠くて。何て言った？"],
  ["help", "!no", "@Q", "e:息子が全然来てくれなくてね。"],
  ["help", "!no", "@Q", "e:ゴミ出しができなくなってきた。"],
  ["help", "!no", "@Q", "e:大丈夫、大丈夫。", "c:そうですか。", "e:でも階段がね、もう上がれないの。"],
  ["condition", "yes", "@Q", "e:元気ですよ。"],
  ["condition", "yes", "@Q", "e:はい、おかげさまで元気です。"],
  ["condition", "yes", "@Q", "e:変わりないよ、元気元気。"],
  ["condition", "yes", "@Q", "e:元気やで。"],
  ["condition", "yes", "@Q", "e:元気にしとうよ。"],
  ["condition", "yes", "@Q", "e:元気にしとるよ。"],
  ["condition", "yes", "@Q", "e:元気だよ、なんともねぇ。"],
  ["condition", "yes", "@Q", "e:はいげんきです"],
  ["condition", "yes", "@Q", "e:調子いいよ。"],
  ["condition", "yes", "@Q", "e:大丈夫です。"],
  ["condition", "no", "@Q", "e:悪いです。"],
  ["condition", "no", "@Q", "e:具合が悪い。"],
  ["condition", "no", "@Q", "e:調子が悪いんです。"],
  ["condition", "no", "@Q", "e:よくないです。"],
  ["condition", "no", "@Q", "e:いいえ、よくありません。"],
  ["condition", "no", "@Q", "e:元気じゃないです。"],
  ["meal", "yes", "@Q", "e:はい、食べました。"],
  ["meal", "yes", "@Q", "e:食べたよ。"],
  ["meal", "yes", "@Q", "e:いただきました。"],
  ["meal", "yes", "@Q", "e:食べたで。"],
  ["meal", "yes", "@Q", "e:食べたばい。"],
  ["meal", "yes", "@Q", "e:食べたよ、ちゃんと。"],
  ["meal", "yes", "@Q", "e:食ったよ。"],
  ["meal", "yes", "@Q", "e:食べたがね。"],
  ["meal", "yes", "@Q", "e:はいたべました"],
  ["meal", "yes", "@Q", "e:しっかり食べました。"],
  ["meal", "no", "@Q", "e:いいえ、食べてません。"],
  ["meal", "no", "@Q", "e:食べてない。"],
  ["meal", "no", "@Q", "e:食べませんでした。"],
  ["meal", "no", "@Q", "e:いいえ。"],
  ["meal", "no", "@Q", "e:食べてないです。"],
  ["meal", "no", "@Q", "e:ううん、食べてない。"],
  ["medication", "yes", "@Q", "e:はい、飲みました。"],
  ["medication", "yes", "@Q", "e:飲んだよ。"],
  ["medication", "yes", "@Q", "e:ちゃんと飲んでます。"],
  ["medication", "yes", "@Q", "e:飲んだで。"],
  ["medication", "yes", "@Q", "e:飲んだばい。"],
  ["medication", "yes", "@Q", "e:飲んだよ、朝いちばんに。"],
  ["medication", "yes", "@Q", "e:飲んだ飲んだ。"],
  ["medication", "yes", "@Q", "e:飲んだがね。"],
  ["medication", "yes", "@Q", "e:はいのみました"],
  ["medication", "yes", "@Q", "e:朝ごはんのあとに飲みました。"],
  ["medication", "no", "@Q", "e:いいえ、飲んでません。"],
  ["medication", "no", "@Q", "e:飲んでない。"],
  ["medication", "no", "@Q", "e:飲みませんでした。"],
  ["medication", "no", "@Q", "e:いいえ。"],
  ["medication", "no", "@Q", "e:飲んでないです。"],
  ["medication", "no", "@Q", "e:忘れました。"],
  ["sleep", "yes", "@Q", "e:はい、よく眠れました。"],
  ["sleep", "yes", "@Q", "e:ぐっすり寝たよ。"],
  ["sleep", "yes", "@Q", "e:眠れたよ。"],
  ["sleep", "yes", "@Q", "e:よう寝たわ。"],
  ["sleep", "yes", "@Q", "e:よう寝たばい。"],
  ["sleep", "yes", "@Q", "e:よう寝れたよ。"],
  ["sleep", "yes", "@Q", "e:よぐ寝だ。"],
  ["sleep", "yes", "@Q", "e:よう寝れたわ。"],
  ["sleep", "yes", "@Q", "e:はいよくねむれました"],
  ["sleep", "yes", "@Q", "e:朝までぐっすりでした。"],
  ["sleep", "no", "@Q", "e:いいえ、眠れませんでした。"],
  ["sleep", "no", "@Q", "e:眠れなかった。"],
  ["sleep", "no", "@Q", "e:寝てない。"],
  ["sleep", "no", "@Q", "e:いいえ。"],
  ["sleep", "no", "@Q", "e:眠れませんでした。"],
  ["sleep", "no", "@Q", "e:寝られなかったです。"],
  ["help", "no", "@Q", "e:いいえ、特にありません。"],
  ["help", "no", "@Q", "e:ないよ。"],
  ["help", "no", "@Q", "e:何もないです。"],
  ["help", "no", "@Q", "e:あらへんよ。"],
  ["help", "no", "@Q", "e:なかよ。"],
  ["help", "no", "@Q", "e:ないよ、なんもありゃせん。"],
  ["help", "no", "@Q", "e:なんもねぇよ。"],
  ["help", "no", "@Q", "e:なんもないわ。"],
  ["help", "no", "@Q", "e:とくにありません"],
  ["help", "no", "@Q", "e:大丈夫です、ありません。"],
  ["help", "yes", "@Q", "e:はい、あります。"],
  ["help", "yes", "@Q", "e:あります。"],
  ["help", "yes", "@Q", "e:困ってます。"],
  ["help", "yes", "@Q", "e:あるんです。"],
  ["help", "yes", "@Q", "e:はい、ひとつあります。"],
  ["help", "yes", "@Q", "e:ええ、あるのよ。"],
];

describe("blind probe: check-in", () => {
  it.each(EXCHANGES)("%s %s: %s %s %s %s", (topic, expected, ...lines) => {
    const turns = lines.map((x) => (x === "@Q" ? { source: "caller", text: QUESTIONS[topic] } : { source: x.startsWith("c:") ? "caller" : "callee", text: x.slice(2) }));
    const got = checkInReport(turns).items.find((i) => i.topic === topic)!.answer;
    if (expected.startsWith("!")) expect(got).not.toBe(expected.slice(1));
    else expect(got).toBe(expected);
  });
  it("two sentences about one topic are one question; two topics in one turn are not", () => {
    const ask = (q: string, a: string) => Object.fromEntries(checkInReport([{ source: "caller", text: q }, { source: "callee", text: a }]).items.map((i) => [i.topic, i.answer]));
    expect(ask("今日の体調はいかがですか。お元気ですか。", "はい").condition).toBe("yes");
    expect(ask("今日の体調はいかがですか。", "はい").condition).toBe("unclear");
    expect(ask("ご飯は食べましたか。お薬は飲みましたか。", "はい")).toMatchObject({ meal: "unclear", medication: "unclear" });
  });
  it("the wider shapes still refuse a negative that looks like an ending", () => {
    const one = (topic: CheckInTopic, a: string) => checkInReport([{ source: "caller", text: QUESTIONS[topic] }, { source: "callee", text: a }]).items.find((i) => i.topic === topic)!.answer;
    expect(one("condition", "元気ねえ")).not.toBe("yes");
    expect(one("help", "大丈夫じゃないです")).toBe("yes");
    expect(one("help", "大丈夫でない")).toBe("yes");
    expect(one("meal", "食べたい")).not.toBe("yes");
    expect(one("sleep", "寝たい")).not.toBe("yes");
    expect(one("medication", "昨日は朝ごはんのあとに飲みました")).not.toBe("yes");
    expect(one("medication", "主人が飲んだ飲んだ")).not.toBe("yes");
  });
});

// ["E" emergency | "C" concern | "N" nothing, line]. E must be an emergency; C must be flagged (an emergency is accepted:
// 「腰いでくてなぁ、歩がんねぇ」 says they cannot walk); N must raise nothing.
// The probe's author later doubted two of its own C rows. Decision, from the care setting:
//  - 「家の鍵をなくした。」 stays a concern: a person who cannot lock the door, or cannot get back in, needs someone to check.
//  - 「耳が聞こえにくくなった。」 stays a concern: a change in hearing is treatable when caught, and decides whether these
//    calls reach the person at all. Both cost staff one look.
const LINES: ["E" | "C" | "N", string][] = [
  ["E", "胸が痛いんです。"],
  ["E", "胸が苦しくて息ができない。"],
  ["E", "息が苦しい。"],
  ["E", "転んで起き上がれないの。"],
  ["E", "助けて。"],
  ["E", "救急車を呼んでください。"],
  ["E", "血が止まらないんです。"],
  ["E", "頭が割れるように痛い。"],
  ["E", "もう死にたい。"],
  ["E", "死んでしまいたい。"],
  ["E", "動けない、床に倒れたまま。"],
  ["E", "右手がしびれて、ろれつが回らない。"],
  ["E", "口がうまく回らんのよ、顔の半分が動かん。"],
  ["E", "血を吐いた。"],
  ["E", "ガスの臭いがする。"],
  ["E", "火が出た、台所が燃えてる。"],
  ["E", "薬を全部飲んでしまった。"],
  ["E", "首を吊ろうと思ってる。"],
  ["E", "胸がぎゅーっと締めつけられる。"],
  ["E", "目の前が真っ暗になって倒れた。"],
  ["E", "立てないんです、足に力が入らなくて。"],
  ["E", "息が、できん、苦しい。"],
  ["E", "胸が痛うてかなわん、息でけへん。"],
  ["E", "こけて立たれへんねん。"],
  ["E", "もう死にたいわ、ほんまに。"],
  ["E", "胸いでくて息でぎね。"],
  ["E", "転んで起ぎらんねぇ、助けでけろ。"],
  ["E", "胸の痛かと、息のできん。"],
  ["E", "こけて立てんとよ、助けてくれんね。"],
  ["E", "胸が痛うて息ができんのんよ。"],
  ["E", "こけて動けんのじゃ。"],
  ["E", "胸が痛てゃあて息ができんがね。"],
  ["E", "転んでまって立てーせん。"],
  ["E", "むねがいたいですいきがくるしい"],
  ["E", "たおれてうごけませんたすけてください"],
  ["E", "きゅうきゅうしゃよんで"],
  ["E", "お父さんが倒れて返事をしないの。"],
  ["E", "主人が息をしてない。"],
  ["E", "意識がもうろうとしてきた。"],
  ["E", "さっきから左の胸から腕にかけて痛い。"],
  ["E", "心臓がおかしい、ドキドキが止まらなくて苦しい。"],
  ["E", "喉に詰まった、餅が。"],
  ["E", "頭を打って血が出てる。"],
  ["E", "お風呂で溺れかけた、まだ息が苦しい。"],
  ["E", "熱が40度あって、体が動かない。"],
  ["E", "吐いて吐いて止まらない、血も混じってる。"],
  ["E", "便が真っ黒で、ふらふらして立てない。"],
  ["E", "急に目が見えなくなった。"],
  ["E", "言葉が出てこない、あの、あれ、舌が。"],
  ["E", "手足が動かない。"],
  ["E", "消えてしまいたい。生きていてもしょうがない。"],
  ["E", "もう生きていたくない。"],
  ["E", "包丁を持ってるの。もう終わりにする。"],
  ["E", "誰かが家に入ってきた、怖い。"],
  ["E", "殴られた。息子に殴られて血が出てる。"],
  ["E", "煙が出てる、家の中が煙だらけ。"],
  ["E", "苦しい…苦しい…"],
  ["E", "痛い痛い痛い、お腹が、助けて。"],
  ["E", "腰を打って全然動けん。骨が折れたかもしれん。"],
  ["E", "足が折れたみたい、変な方向に曲がってる。"],
  ["E", "ぜんそくの発作が、吸入しても、止まらない。"],
  ["E", "インスリンを打ちすぎた、冷や汗が出て震えてる。"],
  ["E", "蜂に刺されて、息がしづらい、体じゅう腫れてきた。"],
  ["E", "寒くて震えが止まらない、暖房が壊れて、もう手の感覚がない。"],
  ["E", "2日間何も飲んでない、起き上がれない。"],
  ["E", "けいれんしてる、妻が。"],
  ["E", "胸が痛い。冷や汗が出る。"],
  ["E", "呼吸ができません。"],
  ["E", "酸素のボンベが空になった。苦しい。"],
  ["E", "階段から落ちた。頭から血が。"],
  ["E", "死のうと思って薬を集めてる。"],
  ["E", "首が締めつけられる感じで、声が出ない。息もしにくい。"],
  ["E", "大量に下血した。"],
  ["E", "救急車…お願い…"],
  ["E", "たすけて、うごけない"],
  ["E", "お腹が激しく痛くて冷や汗が止まらない。"],
  ["E", "さっき一瞬気を失ったみたいで、気がついたら床にいた。"],
  ["E", "半身がしびれて力が入らん。"],
  ["E", "顔がゆがんでるって言われた、片方の手も上がらない。"],
  ["E", "息が吸えない、ゼーゼーいってる。"],
  ["E", "もうだめ、死ぬ、助けて。"],
  ["E", "橋から飛び降りようかと思う。"],
  ["E", "川に入って死のうと思った。"],
  ["E", "ベッドから落ちて、起きれん、痛い。"],
  ["E", "浴槽から出られない、もう1時間入ったまま。"],
  ["E", "やけどした、熱湯をかぶって皮がむけてる。"],
  ["E", "間違えて洗剤を飲んでしまった。"],
  ["E", "血圧が200を超えてて頭がガンガンする、吐き気もする。"],
  ["E", "むねがいたい、いきが、できない"],
  ["E", "おじいさんが倒れとる、呼んでも起きん。"],
  ["C", "最近食欲がなくてね。"],
  ["C", "夜眠れない日が続いてる。"],
  ["C", "さみしい。誰とも話してない。"],
  ["C", "ここ3日、熱が下がらない。"],
  ["C", "ふらふらする。"],
  ["C", "咳が止まらなくてね。"],
  ["C", "膝が痛くて歩きづらい。"],
  ["C", "薬がなくなった。"],
  ["C", "何もやる気が出ない。"],
  ["C", "体重が減ってきた。"],
  ["C", "物忘れがひどくなって、鍋を焦がした。"],
  ["C", "昨日転んだけど、ちょっとあざができただけ。"],
  ["C", "一人で不安なの。"],
  ["C", "お金がなくて食べ物が買えない。"],
  ["C", "ストーブが壊れて寒い。"],
  ["C", "誰にも会ってない、もう1週間。"],
  ["C", "生きがいがないね。"],
  ["C", "足がむくんで靴が履けない。"],
  ["C", "便秘が1週間続いてる。"],
  ["C", "おしっこが出にくい。"],
  ["C", "めまいがする。"],
  ["C", "頭が痛い。"],
  ["C", "お腹の調子が悪くて下痢してる。"],
  ["C", "息子に怒鳴られるのがつらい。"],
  ["C", "知らない人から電話で、お金を振り込めと言われた。"],
  ["C", "耳が聞こえにくくなった。"],
  ["C", "最近よくつまずく。"],
  ["C", "気分が落ち込んでる。"],
  ["C", "泣いてばかりいるの。"],
  ["C", "病院に行けてない、足がなくて。"],
  ["C", "しんどいねん、ずっと。"],
  ["C", "ご飯食べる気せえへんねん。"],
  ["C", "腰いでくてなぁ、歩がんねぇ。"],
  ["C", "ずっときつかとよ。食欲もなか。"],
  ["C", "体がえらいんよ、なんもする気がせん。"],
  ["C", "えらいでかんわ、ご飯も食べれんで。"],
  ["C", "さいきんねむれなくてしょくよくもないです"],
  ["C", "ふらふらしてあるけません"],
  ["C", "熱っぽい。"],
  ["C", "血圧が高いって言われたけど、薬を飲んでない。"],
  ["C", "家の鍵をなくした。"],
  ["C", "水道が止まった。"],
  ["C", "夫が亡くなってから何もする気が起きない。"],
  ["C", "喉が痛くて声が出にくい。"],
  ["C", "手が震えるようになった。"],
  ["C", "夜中に何度もトイレに起きて眠れない。"],
  ["C", "傷が膿んできた。"],
  ["C", "3日お風呂に入ってない、入るのが怖くて。"],
  ["C", "ごはんは1日1回しか食べてない。"],
  ["C", "気持ちが落ち着かなくて、そわそわする。"],
  ["N", "今日はいい天気ですね。"],
  ["N", "元気ですよ、ありがとう。"],
  ["N", "昨日テレビで救急車のドラマを見てたの。"],
  ["N", "隣の田中さんが先月倒れて入院したのよ。"],
  ["N", "去年、胸が痛くて病院に行ったけど何ともなかった。"],
  ["N", "腹が立って死にそうだったわ、あの番組。"],
  ["N", "おかしくて死ぬかと思った。笑いすぎて。"],
  ["N", "孫がかわいくて死にそう。"],
  ["N", "お饅頭が喉から手が出るほど食べたい。"],
  ["N", "息が詰まるような映画だった。"],
  ["N", "胸が痛むニュースだねえ、あの地震。"],
  ["N", "頭が痛い問題だよ、町内会の会費。"],
  ["N", "血の気が引いたよ、値段を見て。"],
  ["N", "足が棒になるまで歩いた。楽しかった。"],
  ["N", "主人は10年前に亡くなりました。"],
  ["N", "昔、火事を出したことがあってね、若い頃。"],
  ["N", "薬はちゃんと飲んでますよ。"],
  ["N", "今日はカレーを食べました。"],
  ["N", "寒くなってきたね。"],
  ["N", "デイサービスでお風呂に入ってきた。"],
  ["N", "娘が明日来てくれるの。"],
  ["N", "昨日はよく眠れました。"],
  ["N", "相撲を見てたら力士が倒れてびっくりした。"],
  ["N", "ニュースで殺人事件のことを言ってた。怖いね。"],
  ["N", "友達が救急車で運ばれたけど、もう退院したって。"],
  ["N", "動けないほど食べちゃった。おいしくて。"],
  ["N", "転んでもただでは起きないよ、私は。"],
  ["N", "死ぬまでに一度、温泉に行きたいね。"],
  ["N", "助けてもらってばかりで、ありがたいことです。"],
  ["N", "息子は消防士で、火事の現場に行ってる。"],
  ["N", "血圧は正常でしたよ、今朝も。"],
  ["N", "胸がいっぱいになったよ、孫の手紙で。"],
  ["N", "腰は去年手術して、もう痛くない。"],
  ["N", "苦しい時代だったねえ、戦後は。"],
  ["N", "ガスの点検の人が来て、問題ないって。"],
  ["N", "元気やで、ぼちぼちやっとるわ。"],
  ["N", "阪神が負けて死にそうや。"],
  ["N", "なんもねぇよ、元気だ。"],
  ["N", "元気にしとうよ。心配せんでよか。"],
  ["N", "カープが勝ったけえ機嫌がええんよ。"],
  ["N", "元気だがね。味噌煮込み食べたでよ。"],
  ["N", "きょうはでいさーびすにいってきました"],
  ["N", "げんきですごはんもたべました"],
  ["N", "はい、はい、聞こえてますよ。"],
  ["N", "もしもし、どなた？"],
  ["N", "倒れた木を片付けてもらったの、台風のあと。"],
  ["N", "血液検査の結果はよかったです。"],
  ["N", "息を切らして孫が走ってきたのよ。"],
  ["N", "今日は病院の日で、先生に順調だって言われた。"],
  ["N", "死んだ母がよくこの煮物を作ってくれた。"],
  ["N", "時代劇で人が斬られて血が出る場面は苦手。"],
  ["N", "熱いお茶が好きでね。"],
  ["N", "痛い出費だったけど、新しい冷蔵庫を買った。"],
  ["N", "眠れないほど楽しみ、明日の旅行。"],
  ["N", "首を長くして待ってるのよ、荷物。"],
  ["N", "薬局で湿布をもらってきた。"],
  ["N", "体操教室で息が上がったけど、気持ちよかった。"],
  ["N", "喉が渇いたからお茶を飲んでる。"],
  ["N", "包丁を研いでもらったら、よく切れるようになった。"],
  ["N", "隣の家が火事になったのは3年前だったかね。"],
];
const level = (text: string) => distressLevel(detectDistress(text));

describe("blind probe: distress", () => {
  it.each(LINES)("%s: %s", (expected, text) => {
    if (expected === "E") expect(level(text)).toBe("emergency");
    else if (expected === "C") expect(level(text)).not.toBeNull();
    else expect(detectDistress(text)).toEqual([]);
  });
  it("the present tense about the speaker wins over a past or other-person frame", () => {
    expect(level("去年手術したんですが、胸が苦しいんです")).toBe("emergency");
    expect(level("去年転んでから足が動かない")).toBe("emergency");
    expect(level("隣の田中さんが先月倒れたのよ、私も今朝から胸が痛い")).toBe("emergency");
    expect(level("主人が倒れた")).toBe("emergency");
    expect(level("お父さんが息をしてないの")).toBe("emergency");
    expect(level("友達が倒れたのよ")).toBe("concern");
    expect(level("昔、死にたいと思ったことがあった")).toBe("concern");
  });
  it("two ordinary concerns stay concerns; a physical one that is not stopping does not", () => {
    expect(level("昨日転んで、腰が痛いんです")).toBe("concern");
    expect(level("咳が止まらなくてね")).toBe("concern");
    expect(level("吐き気が止まらない")).toBe("emergency");
    expect(level("頭が痛くて吐き気もする")).toBe("emergency");
  });
});

const HEARD: [boolean, string][] = [
  [true, "ただいま電話に出ることができません。ピーという発信音の後に、お名前とご用件をお話しください。"],
  [true, "留守番電話サービスセンターにおつなぎします。"],
  [true, "おかけになった電話は、電波の届かない場所にあるか、電源が入っていないため、かかりません。"],
  [true, "おかけになった電話番号は、現在使われておりません。番号をお確かめになって、もう一度おかけ直しください。"],
  [true, "こちらは留守番電話サービスです。発信音の後にメッセージをどうぞ。"],
  [true, "はい、山田です。ただいま留守にしております。ご用の方は発信音のあとにメッセージをお願いします。"],
  [true, "お電話ありがとうございます。丸山商事でございます。本日の営業は終了いたしました。営業時間は平日午前9時から午後6時までです。"],
  [true, "ただいま電話が大変混み合っております。恐れ入りますが、そのまましばらくお待ちください。"],
  [true, "新規のご契約は1を、ご契約内容の確認は2を、その他のお問い合わせは3を押してください。"],
  [true, "この通話は、サービス向上のため録音させていただきます。"],
  [true, "順番におつなぎしております。そのままお待ちください。"],
  [true, "おかけになった電話をお呼びしましたが、お出になりません。"],
  [true, "ただいま近くにおりません。のちほどおかけ直しください。"],
  [true, "留守です。ファックスの方はそのまま送信してください。お電話の方は発信音の後にお話しください。"],
  [true, "Hello, you've reached the voicemail of John Smith. Please leave a message after the beep."],
  [true, "The number you have dialed is not in service. Please check the number and try again."],
  [true, "Thank you for calling. Our office is currently closed. Our business hours are Monday through Friday, 9 a.m. to 5 p.m."],
  [true, "For English, press 2."],
  [true, "Your call is important to us. Please stay on the line and the next available representative will assist you."],
  [true, "メッセージの録音が終わりましたら、シャープを押してください。"],
  [true, "お客様のご都合により、通話ができなくなっております。"],
  [true, "こちらはauお留守番サービスです。"],
  [true, "ただいま電話に出ることができません。留守番電話サービスセンターで伝言をお預かりします。発信音の後に3分以内でお話しください。"],
  [true, "ソフトバンクです。おかけになった電話は、現在電波の届かないところにあります。"],
  [true, "おかけになった電話番号への通話は、おつなぎできません。"],
  [true, "ただいま診療時間外です。急患の方は救急センターまでおかけください。"],
  [true, "誠に勝手ながら、本日は臨時休業とさせていただいております。"],
  [true, "担当者におつなぎします。ただいまの待ち時間はおよそ5分です。"],
  [true, "番号を確認できませんでした。もう一度入力してください。"],
  [true, "内線番号をご存じの方は内線番号を、ご不明な方は0を押してください。"],
  [true, "はい佐藤でございます。あいにく外出しております。お急ぎの方は携帯のほうへお願いします。発信音のあとにどうぞ。"],
  [true, "もしもし、田中です。今出られへんから、ピーって鳴ったらメッセージ入れといて。"],
  [true, "ただいまでんわにでることができませんぴーというはっしんおんのあとにおなまえとごようけんを"],
  [true, "おかけになったでんわはでんぱのとどかないばしょにあるかでんげんがはいっていないため"],
  [true, "こちらは緑川市役所です。ただいまの時間は業務を行っておりません。"],
  [true, "お電話ありがとうございます。音声ガイダンスに従って番号を押してください。"],
  [true, "発信音の後に20秒以内でお話しください。"],
  [true, "おかけになった電話は、お客様の申し出により現在お取り扱いしておりません。"],
  [true, "この電話は迷惑電話防止のため録音されます。お名前をおっしゃってください。"],
  [true, "The person you are trying to reach is unavailable. At the tone, please record your message."],
  [true, "ただいま留守にしています。御用の方はピーと鳴ったらお話しください。"],
  [true, "お電話ありがとうございます。レストラン花です。ただいまの時間は準備中のため、電話に出ることができません。"],
  [true, "現在、回線が混み合っているため、かかりにくくなっております。しばらくたってからおかけ直しください。"],
  [true, "オペレーターにおつなぎする場合は9を押してください。"],
  [true, "We're sorry, all of our agents are busy. Please hold."],
  [false, "はい、もしもし。"],
  [false, "はい、山田です。"],
  [false, "お電話ありがとうございます、丸山商事の佐藤でございます。"],
  [false, "もしもし、どちら様ですか。"],
  [false, "あ、さっき留守電にメッセージ入れてくれた方ですか。"],
  [false, "すみません、主人は今留守にしております。"],
  [false, "留守番電話にしてたつもりだったんだけど、出ちゃった。"],
  [false, "伝言なら私が預かりますよ。"],
  [false, "担当は外出中ですが、ご用件を伺います。"],
  [false, "はい？聞こえないんだけど。"],
  [false, "あー、今ちょっと電話に出られる状況じゃないんで、あとでかけ直します。"],
  [false, "メッセージを残しておきますので、お名前をお願いします。"],
  [false, "営業時間は9時からなんですけど、今日はたまたま早く来てたんですよ。"],
  [false, "本日は休みなんですが、私だけ出てきてます。ご用件は？"],
  [false, "え、誰？"],
  [false, "うん。"],
  [false, "はい、はい。少々お待ちください。"],
  [false, "ピーって音がしたけど、何？"],
  [false, "母は今出かけてます。伝言ありますか。"],
  [false, "はいはい、どちらさん？"],
  [false, "今おらへんで、お父ちゃん。"],
  [false, "はい、もすもす、どぢらさんだべ。"],
  [false, "はい、どなたですかね。"],
  [false, "はいもしもしやまだです"],
  [false, "Hello? Who is this?"],
  [false, "Sorry, he's not available right now. Can I take a message?"],
  [false, "ただいま戻りました、田中です。お待たせしました。"],
  [false, "おかけ間違いじゃないですか。"],
  [false, "電波が悪いみたいで、よく聞こえません。"],
  [false, "お電話代わりました、鈴木です。"],
  [false, "こんにちは。あの、番号を押せって言われても、わからないんですけど。"],
  [false, "今運転中なので、あとでかけ直してもらえますか。"],
  [false, "ただいま、えーと、何だっけ、そうそう、どちら様？"],
  [false, "はい、こちら受付です。ご用件をどうぞ。"],
  [false, "うちは留守番電話はつけてないのよ。"],
];
describe("blind probe: machine or person", () => {
  it.each(HEARD)("machine %s: %s", (machine, text) => expect(isMachineGreeting(text)).toBe(machine));
});

// Rows a second blind set (140 exchanges, 150 lines, 60 heard lines; one- and two-sentence questions) got wrong before
// the fixes it led to. "X" mentions an emergency that is past, resolved, someone else's or a figure of speech: never an emergency.
const SECOND_EXCHANGES: [CheckInTopic, "yes" | "no" | "!yes" | "!no", string, ...string[]][] = [
  ["condition", "yes", "今日の体調はいかがですか。お元気にお過ごしですか。", "e:元気でやっとります。"],
  ["condition", "yes", "今日の体調はいかがですか。お元気にお過ごしですか。", "e:げんきにしてますよ"],
  ["condition", "yes", "お体の調子はどうですか。今日もお元気でいらっしゃいますか。", "e:すこぶる元気です。"],
  ["meal", "yes", "朝ごはんは召し上がりましたか。", "e:食べたんよ、もう。"],
  ["meal", "yes", "今日はお食事をとられましたか。", "e:さっき食っだ。"],
  ["medication", "yes", "お薬はお飲みになりましたか。", "e:朝ごはんのあとに飲んどいたよ。"],
  ["medication", "yes", "今日のお薬についてうかがいます。もうお飲みになりましたか。", "e:飲んだで、さっき。"],
  ["medication", "yes", "お薬の時間ですね。今日のお薬は飲まれましたか。", "e:飲んだんよ。"],
  ["medication", "yes", "今日のお薬はもう飲まれましたか。", "e:飲んだでよ。"],
  ["medication", "yes", "今日のお薬についてうかがいます。もうお飲みになりましたか。", "e:飲みました飲みました。"],
  ["sleep", "yes", "夜はぐっすり眠れましたか。", "e:よう寝たんよ。"],
  ["sleep", "yes", "昨夜はお休みになれましたか。朝までよく眠れましたか。", "e:よう寝れたでよ。"],
  ["sleep", "yes", "昨晩はよく眠れましたでしょうか。", "e:寝た寝た、よく寝た。"],
  ["sleep", "yes", "ゆうべの睡眠はいかがでしたか。よく眠れましたか。", "e:よく眠れたよ、ゆうべは。"],
  ["help", "no", "最近お困りのことはありますか。何か困っていらっしゃることがあれば教えていただけますか。", "e:なんにもあらせんよ。"],
  ["help", "no", "何かお困りごとはありますか。お手伝いが必要なことはございますか。", "e:いまのところとくにありません"],
  ["help", "no", "今、困っていらっしゃることはありますか。", "e:ないない、なんにもない。"],
  ["meal", "!yes", "今日はお食事をとられましたか。", "e:はい、いただきました。", "c:しっかり召し上がれましたか。", "e:お膳はそのまま下げてもらいました。"],
  ["sleep", "!yes", "ゆうべはよくお休みになれましたか。", "e:はい、眠れましたよ。", "c:安心しました。", "e:夜通しラジオを聞いていましたがね。"],
  ["help", "!no", "お困りのことは何かありますか。", "e:ありません。", "c:わかりました。", "e:けど、畑の草が刈れんで近所から苦情が来とる。"],
  ["help", "!no", "最近お困りのことはありますか。何か困っていらっしゃることがあれば教えていただけますか。", "e:大丈夫ですよ。", "c:何よりです。", "e:年金の手紙が来たけど、何を書けばいいのかさっぱりで。"],
];
const SECOND_LINES: ["E" | "C" | "N" | "X", string][] = [
  ["E", "さっきから胸のあたりが重苦しゅうて、脂汗が出てくるんです"],
  ["E", "のどに飴がはまって、せきをしても出てこん、くるしい"],
  ["E", "おとうさんが風呂で沈んどる、引き上げられん"],
  ["E", "さっきから自分がどこにおるのか分からんのです、知らん部屋におる"],
  ["E", "腕をガラスで切って、押さえても押さえても血があふれてくる"],
  ["E", "おぎあがらんねぇ、こしぬげで、ひとばんじゅう台所さ寝でだ"],
  ["E", "もうこの世におってもしょうがない、あした身の回りを片付けて終わりにする"],
  ["E", "練炭を買うてきた、今夜でおしまいにしようと思う"],
  ["E", "てんぷら油に火が入って、天井まで炎が上がっとる"],
  ["E", "暑くて暑くて、汗も出なくなって、手がつって体が起こせない"],
  ["E", "しんぞうがとまりそうにくるしいです"],
  ["E", "ベッドと壁のあいだに挟まって、抜け出せん、もう力が出ん"],
  ["E", "こけて、あしが、うごかん、いたい、だれかきて"],
  ["C", "ここんとこ、一日に一食がやっとです"],
  ["C", "さいふがみあたらん、だれかにとられたかもしれん"],
  ["C", "警察を名乗る人から、キャッシュカードを預かると電話があった"],
  ["C", "息子を名乗る男から、今日中に百万いると言われて、用意しとるところ"],
  ["C", "もう何の楽しみもない、毎日ただ起きて寝るだけ"],
  ["N", "お陰様で、痛いところもかゆいところもありません"],
  ["X", "おととし主人が心筋梗塞で倒れたけど、今はゴルフに行くほど元気"],
  ["X", "息が止まるかと思ったよ、宝くじが当たって"],
  ["X", "心臓が止まるかと思うた、孫が急に後ろから声かけるけえ"],
  ["X", "昔、自殺した同級生がおってね、今でも命日には手を合わせる"],
  ["X", "隣町で火事があったって、けさの新聞に載っとった"],
  ["X", "孫のゲームで、キャラクターが倒れて動けんようになるんよ"],
  ["X", "おとといガス漏れの警報が鳴ったけど、ガス会社が来て直してくれた、もう大丈夫"],
];
const SECOND_HEARD: [boolean, string][] = [
  [true, "木村やけど、今おらんねん。用事あったらピーのあとに言うといて。"],
  [true, "はい、松本ですたい。いま留守にしとりますけん、ピーて鳴ったら用件ば言うてください。"],
  [true, "担当の者が電話に出るまで、音楽を聴きながらお待ちください。"],
  [true, "本日の診療受付は終了しました。夜間の急病は、市の休日夜間診療所へお問い合わせください。"],
  [true, "ただいま、留守番電話に切り替わっております。ファクシミリの方は、スタートボタンを押してください。"],
  [true, "ただいま運転中、もしくは携帯電話の利用を控えなければならない場所にいるため、電話に出られません。"],
  [true, "迷惑電話対策のため、自動で応答しております。ご用の方は、お名前をお話しになってからお待ちください。"],
  [true, "年末年始の休業期間中です。新年は1月5日から通常どおり営業いたします。"],
  [true, "Hi, this is Sarah. I'm away from my phone right now. Leave your name and number and I'll call you back."],
  [true, "Please enter your account number followed by the pound key."],
  [true, "Your estimated wait time is seven minutes. Thank you for your patience."],
];
describe("second blind set: what it found", () => {
  it.each(SECOND_EXCHANGES)("%s %s: %s %s %s %s", (topic, expected, question, ...lines) => {
    const turns = [{ source: "caller", text: question }, ...lines.map((x) => ({ source: x.startsWith("c:") ? "caller" : "callee", text: x.slice(2) }))];
    const got = checkInReport(turns).items.find((i) => i.topic === topic)!.answer;
    if (expected.startsWith("!")) expect(got).not.toBe(expected.slice(1));
    else expect(got).toBe(expected);
  });
  it.each(SECOND_LINES)("%s: %s", (expected, text) => {
    if (expected === "E") expect(level(text)).toBe("emergency");
    else if (expected === "C") expect(level(text)).not.toBeNull();
    else if (expected === "X") expect(level(text)).not.toBe("emergency");
    else expect(detectDistress(text)).toEqual([]);
  });
  it.each(SECOND_HEARD)("machine %s: %s", (machine, text) => expect(isMachineGreeting(text)).toBe(machine));
  it("a question that only carries the verb takes its topic from the sentence before, and only then", () => {
    const ask = (q: string, a: string) => Object.fromEntries(checkInReport([{ source: "caller", text: q }, { source: "callee", text: a }]).items.map((i) => [i.topic, i.answer]));
    expect(ask("今日のお薬についてうかがいます。もうお飲みになりましたか。", "はい").medication).toBe("yes");
    expect(ask("お薬の時間ですね。お散歩は行かれましたか。", "はい").medication).toBe("not_asked");
  });
  it("a follow-up for detail leaves a yes alone; a yes/no asked again needs a yes", () => {
    const run = (...t: string[]) => checkInReport(t.map((x) => ({ source: x.startsWith("c:") ? "caller" : "callee", text: x.slice(2) }))).items.find((i) => i.topic === "meal")!.answer;
    expect(run("c:朝ごはんは召し上がりましたか。", "e:はい、いただきました。", "c:何を召し上がりましたか。", "e:パンと卵です。")).toBe("yes");
    expect(run("c:朝ごはんは召し上がりましたか。", "e:はい、いただきました。", "c:しっかり召し上がれましたか。", "e:お膳はそのまま下げてもらいました。")).toBe("unclear");
  });
  it("a person saying someone cannot come to the phone, in English, is a person", () => {
    expect(isMachineGreeting("Sorry, she can't come to the phone right now, can I take a message?")).toBe(false);
  });
});
