import assert from 'node:assert/strict';
import { launch, freePort, serve, sleep } from './cdp.mjs';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const out = resolve(process.env.QUALITY_OUT_DIR || 'artifacts/quality', 'zoom') + '/';
mkdirSync(out, {recursive:true});
const temp = mkdtempSync(join(tmpdir(), 'oathra-zoom-'));
const port = await freePort();
const url = `http://127.0.0.1:${port}`;
const server = await serve(process.execPath, [resolve('packages/cli/dist/bin.js'),'demo','--no-open','--port',String(port)], {cwd:temp,url});
const page = await launch({width:1440,height:900});
try {
 await page.goto(url);
 const metrics = () => page.js('({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scale:visualViewport.scale,doc:document.documentElement.scrollWidth})');
 const before = await metrics();
 await page.goto('chrome://settings/appearance');
 console.log(await page.js(`(()=>{const list=[];function scan(root){for(const n of root.querySelectorAll('*')){if(n.tagName==='SELECT')list.push({id:n.id,value:n.value,options:[...n.options].map(o=>({value:o.value,text:o.textContent}))});if(n.shadowRoot)scan(n.shadowRoot)}}scan(document);return list})()`));
 const change = await page.js(`(()=>{function scan(root){for(const n of root.querySelectorAll('*')){if(n.tagName==='SELECT'&&[...n.options].some(o=>o.textContent.trim()==='200%')){n.value=[...n.options].find(o=>o.textContent.trim()==='200%').value;n.dispatchEvent(new Event('change',{bubbles:true}));return {id:n.id,value:n.value};}if(n.shadowRoot){const r=scan(n.shadowRoot);if(r)return r}}}return scan(document)})()`);
 await page.goto(url+'/?lang=ja&mode=play');
 const after = await metrics();
 await page.screenshot(out+'zoom.png');
 assert.equal(after.dpr,2); assert.equal(after.scale,1); assert.equal(after.width,720);
 assert.ok(await page.noSidewaysScroll());
 await page.until("document.querySelector('.scenario-btn[data-scenario=restaurant-reservation]')");
 await page.js("document.querySelector('.scenario-btn[data-scenario=restaurant-reservation]').focus()");
 await page.press('Enter');
 await page.until("document.activeElement.id==='play-text'");
 await page.type('はい、お電話ありがとうございます。'); await page.press('Enter');
 await page.until("[...document.querySelectorAll('#transcript .line.callee .say')].some(n=>n.textContent.includes('お電話ありがとうございます'))");
 const callUrl = await page.js('location.href'); const id = new URL(callUrl).searchParams.get('call');
 await page.screenshot(out+'conversation.png');
 await page.js("document.querySelector('#play-hangup').focus()"); await page.press('Enter');
 await page.until("document.querySelector('.save-state')?.textContent.includes('保存済み')");
 const href = await page.js("document.querySelector('.result-actions a[download]').href");
 const artifact = await (await fetch(href)).json();
 assert.equal(artifact.callId,id); assert.equal(artifact.endReason,'cancelled');
 assert.deepEqual(await (await fetch(url+'/api/replays/'+id+'/artifact')).json(),artifact);
 assert.ok(await page.noSidewaysScroll());
 await page.js("document.querySelector('.result-actions a[download]').focus()");
 await page.js("document.querySelector('.result-actions').scrollIntoView({block:'center'})"); await sleep(800);
 await page.js("document.querySelector('.result-actions').scrollIntoView({block:'center'})");
 await sleep(800);
 await page.screenshot(out+'result.png');
 await page.goto(callUrl);
 await page.until("document.querySelector('.save-state')?.textContent.includes('保存済み')");
 assert.equal((await metrics()).dpr,2);
 writeFileSync(out+'artifact.json',JSON.stringify(artifact,null,2));
 writeFileSync(out+'result.json',JSON.stringify({before,change,after,final:await metrics(),callId:id,status:'PASS',observed:'Real Chrome default zoom 200%, no sideways overflow, keyboard start/reply/cancel, saved artifact and replay equality, reload preserves result.',userAgent:await page.js('navigator.userAgent')},null,2));
 console.log({before,change,after});
} finally {await page.close(); server.stop(); rmSync(temp,{recursive:true,force:true});}
